/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.view;

import javax.swing.UIManager;

/**
 *
 * @author Luiz Dorval
 * @since 07/07/2019
 * @version 1.0.1 beta C56
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jmbMenu = new javax.swing.JMenuBar();
        jmAdd = new javax.swing.JMenu();
        jmiAddYacht = new javax.swing.JMenuItem();
        jmiAddProvider = new javax.swing.JMenuItem();
        jmMaintenance = new javax.swing.JMenu();
        jmiMaintenanceYacht = new javax.swing.JMenuItem();
        jmiMaintenanceProvider = new javax.swing.JMenuItem();
        jmExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        jmAdd.setText("Cadastrar");

        jmiAddYacht.setText("Iate");
        jmiAddYacht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddYachtActionPerformed(evt);
            }
        });
        jmAdd.add(jmiAddYacht);

        jmiAddProvider.setText("Fornecedor");
        jmiAddProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddProviderActionPerformed(evt);
            }
        });
        jmAdd.add(jmiAddProvider);

        jmbMenu.add(jmAdd);

        jmMaintenance.setText("Manutenção");

        jmiMaintenanceYacht.setText("Iate");
        jmiMaintenanceYacht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMaintenanceYachtActionPerformed(evt);
            }
        });
        jmMaintenance.add(jmiMaintenanceYacht);

        jmiMaintenanceProvider.setText("Fornecedor");
        jmiMaintenanceProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMaintenanceProviderActionPerformed(evt);
            }
        });
        jmMaintenance.add(jmiMaintenanceProvider);

        jmbMenu.add(jmMaintenance);

        jmExit.setText("Sair");
        jmExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmExitMouseClicked(evt);
            }
        });
        jmbMenu.add(jmExit);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openAddYacht() {
        UIAddYacht addYacht = new UIAddYacht();
        jDesktop.add(addYacht);
        addYacht.setVisible(true);
    }
    
    private void openAddProvider() {
        UIAddProvider addProvider = new UIAddProvider();
        jDesktop.add(addProvider);
        addProvider.setVisible(true);
    }
    
    private void openMaintenenceYacht() {
        UIMaintenenceYacht maintenenceYacht = new UIMaintenenceYacht();
        jDesktop.add(maintenenceYacht);
        maintenenceYacht.setVisible(true);
    }
    
    private void openMaintenenceProvider() {
        UIMaintenenceProvider maintenenceProvider = new UIMaintenenceProvider();
        jDesktop.add(maintenenceProvider);
        maintenenceProvider.setVisible(true);
    }
    
    private void jmExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jmExitMouseClicked

    private void jmiAddYachtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddYachtActionPerformed
        openAddYacht();
    }//GEN-LAST:event_jmiAddYachtActionPerformed

    private void jmiMaintenanceYachtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMaintenanceYachtActionPerformed
        openMaintenenceYacht();
    }//GEN-LAST:event_jmiMaintenanceYachtActionPerformed

    private void jmiAddProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddProviderActionPerformed
        openAddProvider();
    }//GEN-LAST:event_jmiAddProviderActionPerformed

    private void jmiMaintenanceProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMaintenanceProviderActionPerformed
        openMaintenenceProvider();
    }//GEN-LAST:event_jmiMaintenanceProviderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            com.jtattoo.plaf.smart.SmartLookAndFeel.setTheme("Brown-Giant-Font", "INSERT YOUR LICENSE KEY HERE", "my company");
            UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jmAdd;
    private javax.swing.JMenu jmExit;
    private javax.swing.JMenu jmMaintenance;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiAddProvider;
    private javax.swing.JMenuItem jmiAddYacht;
    private javax.swing.JMenuItem jmiMaintenanceProvider;
    private javax.swing.JMenuItem jmiMaintenanceYacht;
    // End of variables declaration//GEN-END:variables
}
